sonar.projectKey=ufro-itp-corfo_pipeline-test
sonar.organization=ufro-itp-corfo
sonar.projectName=pipeline-test

sonar.sources=calculadora
sonar.python.addl.project_python_paths=calculadora
sonar.tests=calculadora
sonar.python.version=3.12
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/Dockerfile
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=calculadora/coverage.xml
